let CONSTANTS = {}

CONSTANTS.TOKEN_TYPE = {
  LOGIN: 1,
  OTP: 2
};

CONSTANTS.ERROR_TYPES = {
    ERROR: 'ERROR',
    DATA_NOT_FOUND: 'DATA_NOT_FOUND',
    BAD_REQUEST: 'BAD_REQUEST',
    MONGO_EXCEPTION: 'MONGO_EXCEPTION',
    ALREADY_EXISTS: 'ALREADY_EXISTS',
    FORBIDDEN: 'FORBIDDEN',
    INTERNAL_SERVER_ERROR: 'INTERNAL_SERVER_ERROR',
    UNAUTHORIZED: 'UNAUTHORIZED'
};

module.exports = CONSTANTS;
